### ISSUE TITLE
Does this angular module support multiple experiments for the same app simultaneously?

### ISSUE THREAD

**Issue by m0rganic** [omouse/angular-google-experiments#4]

**Comment by omouse** [comment]
At the moment, it's a provider which means it loads up once and when you use configure you can set up only one experiment at a time.

However, it wouldn't be too difficult to convert it to a factory that produces new instances of googleExperiment with different settings.

The barrier I see is that for multiple experiments it seems you need a separate ID? Maybe that's changed?
